In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from sklearn import datasets

In [4]:
iris = datasets.load_iris()

In [5]:
X = iris.data
y= iris.target

In [6]:
from sklearn.neighbors import KNeighborsClassifier

In [7]:
knn = KNeighborsClassifier(n_neighbors =1)

In [8]:
knn.fit(X,y)

KNeighborsClassifier(n_neighbors=1)

In [9]:
knn.predict([[3, 5, 4, 2]])

array([2])

In [10]:
print("Predicted target name:",
       iris['target_names'][knn.predict([[3, 5, 4, 2]])])

Predicted target name: ['virginica']


In [11]:
X_new = np.array([[3,5,4,2]])
print("X_new shape: ", X_new.shape)

X_new shape:  (1, 4)


In [12]:
mypredict = knn.predict(X_new)

In [13]:
print("Prediction:", mypredict)
print("Predicted target name:",
       iris['target_names'][mypredict])

Prediction: [2]
Predicted target name: ['virginica']


In [20]:
#X_new = [[3, 5, 4, 2], [5, 4, 3, 2]]
#knn.predict(X_new)

In [21]:
knn = KNeighborsClassifier(n_neighbors=3)

In [22]:
knn.fit(X,y)

KNeighborsClassifier(n_neighbors=3)

In [23]:
knn.predict(X_new)

array([1, 1])

In [24]:
#Logistics Regression use korbo ekhon for other classifier

In [25]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X,y)
lr.predict(X_new)

D:\Anaconda1\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0, 0])